name: "Doctest"
on:
    workflow_dispatch:
    push:
      branches: [ "main" ]
      paths:
        - 'src/toy_crypto/__about__.py'

jobs:
  doctest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      
      - name: sphinx
        run:  uv run --group docs sphinx-build -M doctest  "docs/source" "docs/build"

    